language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t maxgoldschmidt/docker-react -f Dockerfile.dev .
  - docker run maxgoldschmidt/docker-react

script:
  - docker run -e CI=true maxgoldschmidt/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-433091872783"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY